import type { InventoryItem, Order, Product, Promotion, Review } from "./types";

export const demoProducts: Product[] = [
  {
    id: "mystery-scoop",
    name: "Mystery Scoop",
    slug: "mystery-scoop",
    product_type: "mystery_scoop",
    category: "Mystery Scoops",
    description: "A cute surprise box filled with handpicked products from our collection.",
    price: 999,
    image: "/assets/khazana-product-hero.png",
    status: "active",
    average_rating: 4.9,
    review_count: 38,
    variants: [
      { id: "small", name: "Small Scoop", tier: "budget", item_count: "7 basic items + 2 premium items", min_items: 9, max_items: 9, surprise_gift_count: 0, rules: ["Includes 7 basic items", "Includes 2 premium items"], price: 549, compare_at_price: 649, badge: "Small", line: "A cheerful first scoop" },
      { id: "medium", name: "Medium Scoop", tier: "standard", item_count: "12 basic items + 3 premium items", min_items: 15, max_items: 15, surprise_gift_count: 0, rules: ["Includes 12 basic items", "Includes 3 premium items"], price: 999, compare_at_price: 1199, badge: "Medium", line: "Our most balanced mix", is_default: true },
      { id: "large", name: "Large Scoop", tier: "premium", item_count: "15 basic items + 5 premium items", min_items: 20, max_items: 20, surprise_gift_count: 0, rules: ["Includes 15 basic items", "Includes 5 premium items"], price: 1499, compare_at_price: 1799, badge: "Large", line: "For gifting or a big haul" },
    ],
  },
  {
    id: "build-your-own",
    name: "Build Your Own Scoop",
    slug: "build-your-own-scoop",
    product_type: "build_your_own",
    category: "Build Your Scoop",
    description: "An entirely customized scoop packed around your colours, categories, and occasion notes.",
    price: 1199,
    image: "/assets/khazana-product-hero.png",
    status: "active",
    average_rating: 4.8,
    review_count: 21,
    variants: [
      { id: "byo-small", name: "Small Scoop", tier: "budget", item_count: "7 basic items + 2 premium items", min_items: 9, max_items: 9, surprise_gift_count: 0, rules: ["Includes 7 basic items", "Includes 2 premium items"], price: 699, badge: "Small", line: "A few favourites" },
      { id: "byo-medium", name: "Medium Scoop", tier: "standard", item_count: "12 basic items + 3 premium items", min_items: 15, max_items: 15, surprise_gift_count: 0, rules: ["Includes 12 basic items", "Includes 3 premium items"], price: 1199, badge: "Medium", line: "More category variety", is_default: true },
      { id: "byo-large", name: "Large Scoop", tier: "premium", item_count: "15 basic items + 5 premium items", min_items: 20, max_items: 20, surprise_gift_count: 0, rules: ["Includes 15 basic items", "Includes 5 premium items"], price: 1699, badge: "Large", line: "A generous custom bundle" },
    ],
  },
  {
    id: "gift-hampers",
    name: "Gift Hampers",
    slug: "gift-hampers",
    product_type: "individual",
    category: "Gift Hampers",
    description: "Curated gift hampers for special occasions. Packed beautifully and ready to gift.",
    price: 1499,
    image: "/assets/khazana-product-hero.png",
    status: "active",
    average_rating: 4.9,
    review_count: 15,
    variants: [
      { id: "hamper-small", name: "Mini Hamper", tier: "budget", item_count: "5 items + greeting card", min_items: 5, max_items: 5, surprise_gift_count: 0, rules: ["5 items", "Greeting card"], price: 799, badge: "Mini", line: "A small cute gesture" },
      { id: "hamper-standard", name: "Standard Hamper", tier: "standard", item_count: "8 items + greeting card + chocolates", min_items: 8, max_items: 8, surprise_gift_count: 0, rules: ["8 items", "Greeting card", "Chocolates"], price: 1499, badge: "Standard", line: "Perfect for birthdays", is_default: true },
      { id: "hamper-deluxe", name: "Deluxe Hamper", tier: "premium", item_count: "12 items + greeting card + chocolates + plushie", min_items: 12, max_items: 12, surprise_gift_count: 0, rules: ["12 items", "Greeting card", "Chocolates", "Plushie"], price: 2499, badge: "Deluxe", line: "The ultimate gift" }
    ],
  },
  ...[
    ["scrunchie", "Cloud Soft Scrunchie", "Hair Accessories", 89, "✿", "#FFD1DC"],
    ["pen", "Pastel Gel Pen Set", "Cute Pens", 149, "✎", "#E6E6FA"],
    ["mirror", "Pocket Mirror", "Pocket Mirrors", 129, "◐", "#CDF6F0"],
    ["stickers", "Sticker & Note Pack", "Stickers & Notes", 99, "✦", "#FFE8A3"],
    ["clip", "Mini Hair Clip Pair", "Hair Accessories", 79, "♡", "#F0FFF0"],
    ["charm", "Keychain Charm", "Keychains & Charms", 119, "♢", "#D8F5E6"],
    ["mini", "Beauty Mini", "Beauty Minis", 169, "◌", "#FFD6E8"],
    ["gift", "Surprise Gift Add-on", "Surprise Gifts", 199, "✧", "#E4FFFA"],
  ].map(([id, name, category, price, icon, color]) => ({
    id: String(id),
    name: String(name),
    slug: String(id),
    product_type: "individual" as const,
    category: String(category),
    description: `${name} from the KhazanaScoop cute essentials collection.`,
    price: Number(price),
    badge: "Cute",
    icon: String(icon),
    color: String(color),
    status: "active",
    average_rating: 4.7,
    review_count: 12,
    variants: [],
  })),
];

export const demoInventory: InventoryItem[] = [
  { id: "stationery", name: "Stationery minis", category: "Stationery", cost_price: 28, sell_price: 99, stock: 82, low_stock_at: 10, status: "active" },
  { id: "hair", name: "Hair accessories", category: "Hair Accessories", cost_price: 22, sell_price: 89, stock: 54, low_stock_at: 10, status: "active" },
  { id: "charms", name: "Keychains & charms", category: "Keychains & Charms", cost_price: 35, sell_price: 119, stock: 37, low_stock_at: 10, status: "active" },
  { id: "beauty", name: "Beauty minis", category: "Beauty Minis", cost_price: 55, sell_price: 169, stock: 29, low_stock_at: 10, status: "active" },
  { id: "mirrors", name: "Pocket mirrors", category: "Pocket Mirrors", cost_price: 42, sell_price: 129, stock: 21, low_stock_at: 10, status: "active" },
];

export const demoOrder: Order = {
  id: "KS-DEMO-1024",
  customer: {
    name: "Demo Customer",
    phone: "+91 90000 00000",
    email: "demo@example.com",
    address: "Demo address, Jaipur 302001",
  },
  items: [
    {
      product_id: "mystery-scoop",
      product_name: "Mystery Scoop",
      variant_id: "medium",
      variant_name: "Medium Scoop",
      item_count: "12-15 products",
      quantity: 1,
      price: 999,
      preferences: {},
    },
  ],
  order_note: "No earrings, prefer pink stationery.",
  exclusions: "Earrings",
  payment_status: "paid",
  fulfilment_status: "packed",
  subtotal: 999,
  discount_total: 0,
  shipping_fee: 0,
  total: 999,
  promotion_code: null,
  tracking_number: "SHIP123456",
  created_at: new Date().toISOString(),
};

export const demoPromotions: Promotion[] = [
  {
    id: "free-shipping-499",
    name: "Free shipping over 499",
    title: "Free shipping pan India",
    message: "Packed with care",
    promotion_type: "free_shipping",
    discount_type: "none",
    discount_value: 0,
    min_subtotal: 499,
    free_shipping: true,
    automatic: true,
    banner_placement: "top",
    starts_at: new Date().toISOString(),
    product_ids: [],
  },
];

export const demoReviews: Review[] = [
  {
    id: "demo-review-1",
    product_id: "mystery-scoop",
    customer_name: "Aanya",
    rating: 5,
    title: "The Medium Scoop was exactly as promised",
    body: "The basic and premium item counts were correct, and my no-earrings exclusion was followed.",
    verified: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-review-2",
    product_id: "mystery-scoop",
    customer_name: "Riya",
    rating: 5,
    title: "Thoughtful packing",
    body: "A balanced mix of stationery and accessories with clear tier rules before checkout.",
    verified: true,
    created_at: new Date(Date.now() - 86400000 * 8).toISOString(),
  },
];
